apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-demo-app
  namespace: argocd
  annotations:
    # resolves to the 'guestbook' directory
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: prod
  source:
    repoURL: https://github.com/kobimm1/demo-argo.git
    targetRevision: HEAD
    path: helm/my-demo-app
    helm:
      releaseName: my-app
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: env0001
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true